# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Run TestNG Tests
      run: |
        mvn test -DsuiteXmlFile=test-output/testng.xml
      working-directory: /home/runner/work/All-Chat-UI-Test-Automation/All-Chat-UI-Test-Automation
      continue-on-error: true
      id: run-tests

    - name: Save Test Results
      run: |
        mkdir -p testng-reports
        cp -r target/surefire-reports/* testng-reports/
        mvn surefire-report:report -DoutputDirectory=testng-reports/
        grep -o 'Tests run: [0-9]*, Failures: [0-9]*, Errors: [0-9]*, Skipped: [0-9]*' testng-reports/emailable-report.html > testng-results.txt

    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'automation-jobs'
        payload: |
          {
            "text": "Tests Result: ${{ steps.run-tests.outcome }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Tests Result: ${{ steps.run-tests.outcome }}\nWorkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nTests ran: $(cat testng-results.txt)\nTests passed: ${{ steps.run-tests.outputs.num_passed }}\nTests failed: ${{ steps.run-tests.outputs.num_failed }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
