# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run TestNG Tests
      run: |
        mvn test -DsuiteXmlFile=testng.xml
      working-directory: /home/runner/work/All-Chat-UI-Test-Automation/All-Chat-UI-Test-Automation
      id: run-tests

    - name: Upload screenshots of the failed tests
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: /home/runner/work/All-Chat-UI-Test-Automation/All-Chat-UI-Test-Automation/src/main/screenshots/**

    - name: Save TestNG XML report
      if: always()
      run: |
        mv target/surefire-reports/testng-results.xml ${{ github.workspace }}/testng-results.xml
        
    - name: Post to a Slack channel
      if: always()
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'automation-jobs'
        payload: |
          {
            "text": "Tests Result: ${{ steps.run-tests.outcome }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Tests Result: ${{ steps.run-tests.outcome }}\nTotal Test Cases: $(xmllint --xpath "count(//test)" ${{ github.workspace }}/testng-results.xml)\nWorkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n<@U05R1CUTPBN>"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
